comment: false
github_checks:
  annotations: false
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
fixes:
  - "/home/runner/work/xstache/xstache/::"
