export interface JsxRuntime {
    jsx(type: any, props: unknown, key?: any): any;
    jsxs(type: any, props: unknown, key?: any): any;
    Fragment: any;
}

class Context {
    constructor(
        private readonly data: any,
        private readonly parent: Context | null = null,
    ) {}

    public value(keys: string[]) {
        let found = true;
        let value = this.data;
        for (const key of keys) {
            const next = value ? value[key] : undefined;
            if (next) {
                value = next;
            } else {
                found = false;
                break;
            }
        }
        return found ? value : this.parent?.value(keys);
    }

    public section(
        keys: string[],
        implementation: (context: Context, index: number) => any,
        jsxRuntime: JsxRuntime,
    ) {
        const data = this.value(keys);
        if (!data) {
            return undefined;
        }
        const render = (data: any, index: number) =>
            implementation(new Context(data, this), index);
        return Array.isArray(data)
            ? jsxRuntime.jsx(jsxRuntime.Fragment, {
                  children: data.map(render),
              })
            : render(data, 0);
    }
}

/** Signature of the function generated by the `@xstache/jsx` compiler. */
export type Implementation = (context: Context, jsx: JsxRuntime) => any;

const componentFactory =
    (implementation: Implementation, jsxRuntime: JsxRuntime) => (props: any) =>
        implementation(new Context(props), jsxRuntime);

export { componentFactory };
