set quiet

packages := "xstache"

[private]
list:
    @just --list

coverage-html:
    for dir in {{packages}}; do \
        cd $dir && \
            ./vendor/bin/phpunit --coverage-filter src --coverage-html coverage tests; \
    done

coverage-index-htmls:
    for dir in {{packages}}; do \
        echo "file://{{source_directory()}}/$dir/coverage/index.html"; \
    done
