name: Publish Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without actually publishing (dry-run)"
        type: boolean
        default: true

jobs:
  javascript_build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: javascript
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
          cache-dependency-path: "javascript/pnpm-lock.yaml"
      - run: "pnpm install"
      - run: "pnpm run build"
      # Run installation again now that necessary `dist` JavaScript files have
      # been built.
      - run: "pnpm install"
      - run: "pnpm test"
      - uses: actions/upload-artifact@v4
        with:
          name: javascript
          path: javascript
  javascript_publish:
    runs-on: ubuntu-latest
    needs: javascript_build_and_test
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        package:
          - xstache
          - "@xstache/ast"
          - "@xstache/jsx"
          - "@xstache/jsx-runtime"
          - "@xstache/parse"
    continue-on-error: true
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: javascript
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          set -eo pipefail
          filename=$(pnpm pack --json | jq --raw-output ".filename")
          npm publish --provenance --access public ${{inputs.dry_run && '--dry-run' || ''}} $filename
        id: publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: packages/${{matrix.package}}
